### ISSUE TITLE
About the "bundle.pth" to resume training VG-HuBERT

### ISSUE THREAD

**Issue by tarudesu** [jasonppy/word-discovery#3]
Hi! I have some problem with training the VG-HuBERT. I want to continue to train the VG-HuBERT (3) on another dataset. However, the released file called "best_bundle.pth" seems like do not have the "indices" as well as "optimizer", which are demanded in the code for training. 

Could you share the "bundle.pth" for the best case, please? Or, is there any other solutions? Thank you in advance!

@jasonppy

**Comment by jasonppy** [comment]
Thanks for your issue!

"indices" and "optimizer" are not applicable in your case - 

"indices" are a record for the sampler for sampling data point from the dataloader, this way even if we interrupt the trainining in the middle of an epoch, when we resume it, the sampler can start where we left off, instead of going through the entire dataset from the begining

"optimizer" is the optimizer state

since you are loading the weight to train the model on a different dataset, you need sampler and the optimizer to start from the begining.

I suggest modifying the Trainer, and add an option to load the pretrained vghubert weights, for further training

**Comment by tarudesu** [comment]
Thank you so much for you explanation! 

Otherwise, could I ask you about the VG-Wav2Vec? How was it trained? Could I have the checkpoint of that?

@jasonppy

**Comment by tarudesu** [comment]
Excuse me, sorry for asking a lot. But could I have the scripts (or something) to train the VG-Wav2Vec? And also the scripts for generating the visualization of HuBERT (like the image you put at the top of the first page). Thank you so much in advance.

**Comment by jasonppy** [comment]
sorry for the late reply.

vg-w2v2 is trained exactly the same as vg-hubert. Just need to change the this line https://github.com/jasonppy/word-discovery/blob/master/scripts/training.sh#L13 to path to a pretrained w2v2 weights

**Comment by tarudesu** [comment]
Thank you so much. And some more like which layer that you use for evaluating VG-W2V2? I am kind curious about how to know which one is the best layer for the task. Please let me know. @jasonppy

**Comment by jasonppy** [comment]
No problem. Layer 9 and 10 with attn threshold of 0.8 or 0.7 are the best for the three tasks. In particular, layer 9 with attn threshold of 0.8 on vg-w2v2_5 gives the best boundary number among all vg-w2v2 models (but still underperforms vg-hubert_3)

**Comment by jasonppy** [comment]
Do you mean VG-HuBERT? the visualization code: https://github.com/jasonppy/word-discovery/blob/master/visualize_cls_attn.ipynb. For HuBERT you just need to change how you get cls_attn_weights in function compact_plot

**Comment by tarudesu** [comment]
I see. Thank you so much. For the VG-W2V2, could I have your final checkpoint of that model? @jasonppy

**Comment by jasonppy** [comment]
No problem! I'm sorry but I no longer have that checkpoint. Training the model should just require a change in L13 in training.sh
